### PR TITLE
Adding AML Extension Language Support Documentation

### PR DESCRIPTION
**Pull request by SiddhanthUnnithan**
# PR into Azure/azureml-v2-preview

## Checklist

I have:

- [X] read and followed the contributing guidelines

## Changes

- Added "Tooling Setup" section for VS Code and AML extension language support.
- Added images folder in docs/overview/ to store pic and GIF content

### CODE REVIEW

**Review by lostmygithubaccount — CHANGES_REQUESTED** [review]
you need to edit the sidebar.js file to add the article to the sidebar, otherwise it will be unlisted on the site

**Comment by danielsc** [comment]
looking great!
I have 2 thing: 
1. you are not linked into the TOC -- you should either link to from index.rst or from installation.rst
2. /images/resource_diagnostics.gif is 404

**Comment by SiddhanthUnnithan** [comment]
index.rst has been updated and I've added the resource_diagnostics GIF

**Review by danielsc — APPROVED** [review]

**Comment by SiddhanthUnnithan** [comment]
@lostmygithubaccount index.rst has been updated to include the tooling link. Let me know if there's anything else required.

**Pull request merged**
